<?php
$labels = [
    'name'                       => esc_html__( 'Categories', 'control-listings' ),
    'singular_name'              => esc_html__( 'Category', 'control-listings' ),
    'menu_name'                  => esc_html__( 'Categories', 'control-listings' ),
    'search_items'               => esc_html__( 'Search Categories', 'control-listings' ),
    'popular_items'              => esc_html__( 'Popular Categories', 'control-listings' ),
    'all_items'                  => esc_html__( 'All Categories', 'control-listings' ),
    'parent_item'                => esc_html__( 'Parent Category', 'control-listings' ),
    'parent_item_colon'          => esc_html__( 'Parent Category:', 'control-listings' ),
    'edit_item'                  => esc_html__( 'Edit Category', 'control-listings' ),
    'view_item'                  => esc_html__( 'View Category', 'control-listings' ),
    'update_item'                => esc_html__( 'Update Category', 'control-listings' ),
    'add_new_item'               => esc_html__( 'Add New Category', 'control-listings' ),
    'new_item_name'              => esc_html__( 'New Category Name', 'control-listings' ),
    'separate_items_with_commas' => esc_html__( 'Separate categories with commas', 'control-listings' ),
    'add_or_remove_items'        => esc_html__( 'Add or remove categories', 'control-listings' ),
    'choose_from_most_used'      => esc_html__( 'Choose most used categories', 'control-listings' ),
    'not_found'                  => esc_html__( 'No categories found.', 'control-listings' ),
    'no_terms'                   => esc_html__( 'No categories', 'control-listings' ),
    'filter_by_item'             => esc_html__( 'Filter by category', 'control-listings' ),
    'items_list_navigation'      => esc_html__( 'Categories list pagination', 'control-listings' ),
    'items_list'                 => esc_html__( 'Categories list', 'control-listings' ),
    'most_used'                  => esc_html__( 'Most Used', 'control-listings' ),
    'back_to_items'              => esc_html__( '&larr; Go to Categories', 'control-listings' ),
    'text_domain'                => esc_html__( 'control-listings', 'control-listings' ),
];
$args = [
    'label'              => esc_html__( 'Categories', 'control-listings' ),
    'labels'             => $labels,
    'description'        => '',
    'public'             => true,
    'publicly_queryable' => true,
    'hierarchical'       => true,
    'show_ui'            => true,
    'show_in_menu'       => true,
    'show_in_nav_menus'  => true,
    'show_in_rest'       => true,
    'show_tagcloud'      => true,
    'show_in_quick_edit' => true,
    'show_admin_column'  => true,
    'query_var'          => true,
    'sort'               => false,
    'meta_box_cb'        => 'post_categories_meta_box',
    'rest_base'          => '',
    'rewrite'            => [
        'slug'         => '/'.control_listings_get_listings_archive_slug(),
        'with_front'   => false,
        'hierarchical' => false,
    ],
];
return $args;