<?php
$labels = [
    'name'                       => esc_html__( 'Tags', 'control-listings' ),
    'singular_name'              => esc_html__( 'Tag', 'control-listings' ),
    'menu_name'                  => esc_html__( 'Tags', 'control-listings' ),
    'search_items'               => esc_html__( 'Search Tags', 'control-listings' ),
    'popular_items'              => esc_html__( 'Popular Tags', 'control-listings' ),
    'all_items'                  => esc_html__( 'All Tags', 'control-listings' ),
    'parent_item'                => esc_html__( 'Parent Tag', 'control-listings' ),
    'parent_item_colon'          => esc_html__( 'Parent Tag:', 'control-listings' ),
    'edit_item'                  => esc_html__( 'Edit Tag', 'control-listings' ),
    'view_item'                  => esc_html__( 'View Tag', 'control-listings' ),
    'update_item'                => esc_html__( 'Update Tag', 'control-listings' ),
    'add_new_item'               => esc_html__( 'Add New Tag', 'control-listings' ),
    'new_item_name'              => esc_html__( 'New Tag Name', 'control-listings' ),
    'separate_items_with_commas' => esc_html__( 'Separate tags with commas', 'control-listings' ),
    'add_or_remove_items'        => esc_html__( 'Add or remove tags', 'control-listings' ),
    'choose_from_most_used'      => esc_html__( 'Choose most used tags', 'control-listings' ),
    'not_found'                  => esc_html__( 'No tags found.', 'control-listings' ),
    'no_terms'                   => esc_html__( 'No tags', 'control-listings' ),
    'filter_by_item'             => esc_html__( 'Filter by tag', 'control-listings' ),
    'items_list_navigation'      => esc_html__( 'Tags list pagination', 'control-listings' ),
    'items_list'                 => esc_html__( 'Tags list', 'control-listings' ),
    'most_used'                  => esc_html__( 'Most Used', 'control-listings' ),
    'back_to_items'              => esc_html__( '&larr; Go to Tags', 'control-listings' ),
    'text_domain'                => esc_html__( 'control-listings', 'control-listings' ),
];
$args = [
    'label'              => esc_html__( 'Tags', 'control-listings' ),
    'labels'             => $labels,
    'description'        => '',
    'public'             => true,
    'publicly_queryable' => true,
    'hierarchical'       => false,
    'show_ui'            => true,
    'show_in_menu'       => true,
    'show_in_nav_menus'  => true,
    'show_in_rest'       => true,
    'show_tagcloud'      => true,
    'show_in_quick_edit' => true,
    'show_admin_column'  => false,
    'query_var'          => true,
    'sort'               => false,
    'meta_box_cb'        => 'post_tags_meta_box',
    'rest_base'          => '',
    'rewrite'            => [
        'slug'         => '/'.control_listings_get_listings_archive_slug().'/tag',
        'with_front'   => false,
        'hierarchical' => false,
    ],
];

return $args;