<?php
defined( 'ABSPATH' ) || exit;
$labels = [
    'name'                     => esc_html__( 'Listings', 'control-listings' ),
    'singular_name'            => esc_html__( 'Listing', 'control-listings' ),
    'add_new'                  => esc_html__( 'Add New', 'control-listings' ),
    'add_new_item'             => esc_html__( 'Add New Listing', 'control-listings' ),
    'edit_item'                => esc_html__( 'Edit Listing', 'control-listings' ),
    'new_item'                 => esc_html__( 'New Listing', 'control-listings' ),
    'view_item'                => esc_html__( 'View Listing', 'control-listings' ),
    'view_items'               => esc_html__( 'View Listings', 'control-listings' ),
    'search_items'             => esc_html__( 'Search Listings', 'control-listings' ),
    'not_found'                => esc_html__( 'No events found.', 'control-listings' ),
    'not_found_in_trash'       => esc_html__( 'No events found in Trash.', 'control-listings' ),
    'parent_item_colon'        => esc_html__( 'Parent Listing:', 'control-listings' ),
    'all_items'                => esc_html__( 'All Listings', 'control-listings' ),
    'archives'                 => esc_html__( 'Listing Archives', 'control-listings' ),
    'attributes'               => esc_html__( 'Listing Order', 'control-listings' ),
    'insert_into_item'         => esc_html__( 'Insert into event', 'control-listings' ),
    'uploaded_to_this_item'    => esc_html__( 'Uploaded to this event', 'control-listings' ),
    'featured_image'           => esc_html__( 'Featured image', 'control-listings' ),
    'set_featured_image'       => esc_html__( 'Set banner image', 'control-listings' ),
    'remove_featured_image'    => esc_html__( 'Remove banner image', 'control-listings' ),
    'use_featured_image'       => esc_html__( 'Use as banner image', 'control-listings' ),
    'menu_name'                => esc_html__( 'Listings', 'control-listings' ),
    'filter_items_list'        => esc_html__( 'Filter events list', 'control-listings' ),
    'filter_by_date'           => '',
    'items_list_navigation'    => esc_html__( 'Listings list navigation', 'control-listings' ),
    'items_list'               => esc_html__( 'Listings list', 'control-listings' ),
    'item_published'           => esc_html__( 'Listing published.', 'control-listings' ),
    'item_published_privately' => esc_html__( 'Listing published privately.', 'control-listings' ),
    'item_reverted_to_draft'   => esc_html__( 'Listing reverted to draft.', 'control-listings' ),
    'item_scheduled'           => esc_html__( 'Listing scheduled.', 'control-listings' ),
    'item_updated'             => esc_html__( 'Listing updated.', 'control-listings' ),
    'text_domain'              => esc_html__( 'control-listings', 'control-listings' ),
];
return [
    'label'               => esc_html__( 'Listings', 'control-listings' ),
    'labels'              => apply_filters( 'control_listings_post_type_listing_labels', $labels),
    'description'         => esc_html__( 'Create, manage, and monetize a local or global directory site.', 'control-listings' ),
    'public'              => true,
    'hierarchical'        => false,
    'exclude_from_search' => false,
    'publicly_queryable'  => true,
    'show_ui'             => true,
    'show_in_nav_menus'   => true,
    'show_in_admin_bar'   => true,
    'show_in_rest'        => false,
    'query_var'           => true,
    'can_export'          => true,
    'delete_with_user'    => true,
    'has_archive'         => control_listings_get_listings_archive_slug(),
    'rest_base'           => control_listings_get_listings_archive_slug(),
    'show_in_menu'        => true,
    'menu_position'       => '',
    'menu_icon'           => apply_filters( 'control_listings_post_type_listing_icon', 'dashicons-calendar-alt'),
    'capability_type'     => 'post',
    'supports'            => ['title', 'editor', 'thumbnail', 'excerpt', 'author', 'comments', 'page-attributes', 'revisions'],
    'taxonomies'          => ['listing_cat', 'listing_tag'],
    'rewrite'             => [
        'slug'       => apply_filters( 'control_listings_post_type_listing_rewrite_slug', 'listing'),
        'with_front' => false,
    ],
];